CUDA_VISIBLE_DEVICES=4,5,6,7 python train_ic15_ic13.py \
    --train_data_path /youedata/dengjinhong/zjw/dataset/icdar2015/ch4_training_images/ \
    --train_gt_path /youedata/dengjinhong/zjw/dataset/icdar2015/ch4_training_localization_transcription_gt/ \
    --target_data_path /youedata/dengjinhong/zjw/dataset/icdar2015/ch4_training_images/ \
    --target_gt_path /youedata/dengjinhong/zjw/dataset/icdar2015/ch4_training_localization_transcription_gt/ \
    --val_data_path /youedata/dengjinhong/zjw/dataset/icdar2013/Challenge2_Test_Task12_Images/ \
    --val_gt_path /youedata/dengjinhong/zjw/dataset/icdar2013/gt/ \
    --checkpoint ./checkpoint/ \
    --fold baseline_IC15_IC13 \
    --batch_size 32 \
    --lr 1e-3 \
    --num_workers 8 \
    --epoch 200 \
    --save_interval 5 \
    --log ./log/ \
